### ISSUE TITLE
Showing of MAFF meta data

### ISSUE THREAD

**Issue by StefanRank** [ChrisBertrandDotNet/OpenMAFF#1]
The maff ZIP file contains a file "index.rdf" which has some useful metadata like original URL and more. See [http://maf.mozdev.org/maff-specification.html](url)
Old MAF plugin for Firefox has shown this original URL on the top of each page. Very useful and convenient to jump to the original URL of the stored web page.
Are there plans to add this feature?

**Comment by ChrisBertrandDotNet** [comment]
Yes, I just added a feature I planned for a long time: a banner is displayed at the top of the web page, which contains a link to the original web address.
This banner can been hidden (there is a kind of button on the right).
This feature is available in the version 1.5, please visit [the releases](https://github.com/ChrisBertrandDotNet/OpenMAFF/releases/latest).
